server:
  port: 8080
i:
  outbound:
    port: 9091
# 配置redis
# spring.redis.host
i.freeswitch:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.68.101:3306/freeswitch?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&useAffectedRows=true&useSSL=false
      username: root
      password: root

